### ISSUE TITLE
Cursor not working as expected

### ISSUE THREAD

**Issue by mlongoria1** [BeastCode/VSCode-Angular-TypeScript-Snippets#103]
So when following these simple instructions on a .html file:
https://github.com/BeastCode/VSCode-Angular-TypeScript-Snippets/raw/master/images/ngForSnippet.gif

The "cursor" does not change both instances of item to hero at the same time. I have to change the first instance of item to "hero" then press tab and change the second instance to "heros"

But this example gif shows that you should only have to type hero one time and it will fix it in both places.

Am I missing something very simple here? I am brand new to Angular and this plugin so sorry in advance if this is a newb question.

**Comment by BeastCode** [comment]
I should update the gif. It used to work this way, but it turned out to be a bad idea since it will only work for some english nouns. "Hero" and "item", but if you type in scarf you would get scarfs and not scarves. While it works pretty well for english nouns and doesn't work at all in many other languages.

Thanks for entering a potential issue, I hope you enjoy Angular and let me know if there are an snippets you're missing.  -Mike
