### ISSUE TITLE
what i typed didn't match the prefixs,but it shows snippets

### ISSUE THREAD

**Issue by xuniaoji** [BeastCode/VSCode-Angular-TypeScript-Snippets#97]
for example:
i typed 'aa',it will show some snppets,like t-afterAll,t-afterEach,ngxs-action-payload,
i typed 'payload',it will show 'ngxs-action-payload',

it's not start with prefix

**Comment by BeastCode** [comment]
Hi,
"t-afterAll,t-afterEach,ngxs-action-payload" will are all valid intellisense suggestions, since they contains two a's just like typed. Space triggers intellisense and then it's like a wildcard match.
This is the built in behavior by VSCode, you can see the same example here:
https://code.visualstudio.com/docs/editor/intellisense#_intellisense-features
You can change some of your local settings for intellisense (see further down in the same link), but I don't know of anything that would turn this off.

Thanks for adding the issue and let me know if you have any suggestions for enhancements.
